server:
  port: 8000
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///E:/Serivce-Config-Repo/Service-Config-Repo
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
