server:
  port: 8001
  ssl:
    enabled: true
    #key-store: classpath:server.p12
    trust-store: file:///C:/ssl/server.p12
    trust-store-password: QWas!@34
    key-store: file:///C:/ssl/server.p12
    key-store-password: QWas!@34
    key-store-type: PKCS12
    key-alias: server-ssl-key
#r2dbc
spring:
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:pool:mariadb://192.168.1.101:3306/project
    username: root
    password: QWas!@34
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name : GlobalFilter
          args :
            baseMessage : Spring Cloud Gateway Global Filter
            preLogger   : true
            postLogger  : true
      routes:
        - id : authservice
          uri : lb://authservice
          predicates : 
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
            - CustomFilter
        - id : contentservice
          uri : lb://contentservice
          predicates : 
            - Path=/content/**
          filters:
            - RewritePath=/content/(?<segment>.*), /$\{segment}
            - CustomFilter


eureka:
  instance:
    instance-id: ${spring.application.instance_id:${random.value}}:${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    disable-delta: true
    registry-fetch-interval-seconds: 5
    service-url.defaultZone: http://root:QWas1234@192.168.1.102:8761/eureka

logging:
  level:
    com:
      netflix:
        discovery:
          DiscoveryClient: ERROR

management:
  endpoints:
    web:
      exposure:
        include: '*'
