spring:
  profiles:
    active: default
  application:
    name: contentservice
  config:
    #import: optional:configserver:http://127.0.0.1:8761
    import: optional:configserver:http://192.168.1.102:8761
