version: '3.8'
services:
  center-server:
    image: center-server
    container_name: center-server-container
    ports:
      - "8761:8761"
    networks:
      - msa-network
    volumes:
      - 'D:/server-yml:/server-yml/'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://root:QWas1234@192.168.1.101:8761/eureka/apps"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s

  gateway-server:
    image: gateway-server
    container_name: gateway-server-container
    ports:
      - "8001:8001"
    networks:
      - msa-network
    depends_on:
      center-server:
        condition: service_healthy

networks:
  msa-network:
    driver: bridge