server:
  port: 0
spring:
  main:
    web-application-type: reactive
  #datasource:
    #url: jdbc:mariadb://192.168.1.101:3306/project?characterEncoding=UTF-8&serverTimezone=UTC
    #username: root
    #password: QWas!@34
    #driver-class-name: org.mariadb.jdbc.Driver
  r2dbc:
    url: r2dbc:pool:mariadb://192.168.1.101:3306/project?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: QWas!@34
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true         #모든 SQL문을 콘솔로 출력
        format_sql: true       #JPA 실행쿼리 가독성있게 표현
        use_sql_comments: true #SQL문 이외에 추가적인 정보 출력
  security:
    user:
      name: root
      password: QWas1234
      
logging:
  level:
    org.springframework.r2dbc.core: debug
    org.springframework.data.r2dbc.core.DefaultDatabaseClient: DEBUG
    com:
      netflix:
        discovery:
          DiscoveryClient: ERROR

eureka:
  instance:
    hostname: 192.168.1.102  # 실제 IP 주소
    instance-id: ${spring.application.instance_id:${random.value}}:${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
    enable-self-preservation: true
  client:
    register-with-eureka: true
    fetch-registry:       true
    disable-delta:        true
    registry-fetch-interval-seconds: 5
    service-url.defaultZone: http://root:QWas1234@192.168.1.101:8761/eureka

jwt:
  header : Authorization #X-AUTH-TOKEN
  secretkey : secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey
  expiration : 600000  

management:
  endpoints:
    web:
      exposure:
        include: '*'
message:
  security:
    allow-ip-list: 127.0.0.1, 192.168.1.128, 192.168.1.101, 192.168.1.102
  kafka:
    producer:
      bootstrap-servers: 192.168.101:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      topic:
        name: TestTopic
 